---
- name: Despliegue de clúster de Kubernetes en GKE
  hosts: localhost
  gather_facts: false
  vars:
    nombre_cluster: '{{ lookup("env", "GCP_CLUSTER_NAME") }}'
    project: alambre
    #'{{ lookup("env", "GPC_PROJECT") }}'
    region: '{{ lookup("env", "GCP_REGION") }}'
    node_pool_name: 'default-pool'
    node_count: '{{ lookup("env", "GPC_NODES_NUMBER") }}'
    machine_type: 'n1-standard-2'
    service_account_file: '{{ lookup("env", "GCP_SA_KEY_FILE") }}'

  tasks:
    - name: Imprimir la ruta del archivo de servicio de cuenta
      debug:
        var: service_account_file

    - name: Crear clúster de Kubernetes en GKE
      google.cloud.gcp_container_cluster:
        name: '{{ nombre_cluster }}'
        initial_node_count: '{{ node_count }}'
        project: '{{ project }}'
        zone: '{{ region }}-a'
        location: '{{ region }}-a'
        node_config:
          machine_type: '{{ machine_type }}'
        auth_kind: serviceaccount
        service_account_file: '{{ service_account_file}}'
        state: present
      register: result

    - name: Obtener archivo de configuración de Kubernetes
      google.cloud.gcp_container_cluster_info:
        project: '{{ project }}'
        location: '{{ region }}-a'
        auth_kind: serviceaccount
        service_account_file: '{{ service_account_file }}'

    - name: Descargar credenciales del cluster
      gcp_container_cluster_info:
        project: '{{ project }}'
        auth_kind: serviceaccount
        service_account_file: '{{ service_account_file }}'
        location: '{{ region }}-a'
      register: cluster_info
  
#    - name: Escribir archivo de kubeconfig
#      copy:
#        content: '{{ cluster_info.kubeconfig.content | b64decode }}'
#        dest: '{{ playbook_dir }}/kubeconfig.yaml'
#        mode: 0600
#
#    - name: Instalar kubectl
#      become: true
#      apt:
#        name: kubectl
#        update_cache: yes
#      when: '"kubectl" not in inventory_hostname'
#disk_size_gb: 500
#name: '{{ nombre_cluster }}'
