---
- name: Despliegue de clúster de Kubernetes en GKE
  hosts: localhost
  gather_facts: false
  vars:
    nombre_cluster: '{{ lookup("env", "GCP_CLUSTER_NAME") }}'
    project: alambre
    #'{{ lookup("env", "GPC_PROJECT") }}'
    region: '{{ lookup("env", "GCP_REGION") }}'
    node_pool_name: 'default-pool'
    node_count: '{{ lookup("env", "GPC_NODES_NUMBER") }}'
    machine_type: 'n1-standard-2'
    service_account_file: '{{ lookup("env", "GCP_SA_KEY_FILE") }}'

  tasks:
    - name: Imprimir la ruta del archivo de servicio de cuenta
      debug:
        var: service_account_file

    - name: Crear clúster de Kubernetes en GKE
      google.cloud.gcp_container_cluster:
        name: '{{ nombre_cluster }}'
        project: '{{ project }}'
        zone: '{{ region }}-a'
        location: '{{ region }}-a'
        machine_type: '{{ machine_type }}'
        auth_kind: serviceaccount
        service_account_file: '{{ service_account_file}}'
        state: present
      register: result
    - name: Crear pool de  nodos
      google.cloud.gcp_container_node_pool:
        name: 'node-pool-{{  nombre_cluster}}'
        initial_node_count: '{{ node_count }}'
        cluster: "{{ nombre_cluster }}"
        config:
          disk_size_gb: 80
          disk_type: pd-ssd
          machine_type: n1-standard-2
        location: '{{ region }}-a'
        auth_kind: serviceaccount
        service_account_file: '{{ service_account_file}}'
        state: present
        project: '{{ project }}'
      register: result
    - name: Mostrar salida
      debug:
        var: output