---
- name: Despliegue de clúster de Kubernetes en GKE
  hosts: localhost
  gather_facts: false
  vars:
    project_id: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
    cluster_name: "{{ lookup('env', 'GCP_CLUSTER_NAME') }}"
    region: "{{ lookup('env', 'GCP_REGION') }}"
    node_pool_name: "default-pool"
    node_count: 2
    machine_type: "n1-standard-2"
    service_account_key: "{{ lookup('env', 'GCP_SA_KEY') }}"

  tasks:
    - name: Crear clúster de Kubernetes en GKE
      google.cloud.gcp_container_cluster:
        name: "{{ cluster_name }}"
        initial_node_count: "{{ node_count }}"
        project: "{{ project_id }}"
        location: "{{ region }}-a"
        node_config:
          machine_type: "{{ machine_type }}"
          disk_size_gb: 500
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_key }}"
        state: present
      register: result

    - name: Obtener archivo de configuración de Kubernetes
      google.cloud.gcp_container_cluster_info:
        name: "{{ cluster_name }}"
        project: "{{ project_id }}"
        location: "{{ region }}-a"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_key }}"

    - name: Copiar archivo de configuración de Kubernetes
      copy:
        src: "{{ lookup('env', 'HOME') }}/.kube/config"
        dest: "~/.kube/config"
        remote_src: yes
        mode: 0600

    - name: Instalar kubectl
      become: true
      apt:
        name: kubectl
        update_cache: yes
      when: "'kubectl' not in inventory_hostname"
