---
- name: Despliegue de clúster de Kubernetes en GKE
  hosts: localhost
  gather_facts: false
  vars:
    project_id: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
    cluster_name: alambre-cluster-gke-01
    region: "{{ lookup('env', 'GCP_REGION') }}"
    node_pool_name: "default-pool"
    node_count: 2
    machine_type: "n1-standard-2"
    service_account_file: "{{ lookup('env', 'GCP_SA_KEY') }}"

  tasks:
    - name: Crear clúster de Kubernetes en GKE
      google.cloud.gcp_container_cluster:
        name: "alambre-cluster-gke-01"
        initial_node_count: "{{ node_count }}"
        project: "{{ project_id }}"
        location: "{{ region }}-a"
        node_config:
          machine_type: "{{ machine_type }}"
          disk_size_gb: 500
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file}}"
        state: present
      register: result

    - name: Obtener archivo de configuración de Kubernetes
      google.cloud.gcp_container_cluster_info:
        name: "{{ cluster_name }}"
        project_id: "{{ project_id }}"
        location: "{{ region }}-a"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"

    - name: Descargar credenciales del cluster
      gcp_container_cluster_info:
        name: "{{ cluster_name }}"
        project_id: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        location: "{{ region }}-a"
      register: cluster_info
  
    - name: Escribir archivo de kubeconfig
      copy:
        content: "{{ cluster_info.kubeconfig.content | b64decode }}"
        dest: "{{ playbook_dir }}/kubeconfig.yaml"
        mode: 0600

    - name: Instalar kubectl
      become: true
      apt:
        name: kubectl
        update_cache: yes
      when: "'kubectl' not in inventory_hostname"
