name: Creacion cluster GKE

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependencias de Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible google-auth requests

    - name: Ejecutar playbook de Ansible
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GPC_SA_KEY }}
      run: |
        ansible-playbook -i hosts playbook.yml