name: Crear cluster de Kubernetes GKE en GCP

on:
  workflow_dispatch: {}
    
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      #- name: Copiar credenciales
      #  run: |
      #    echo '${{ secrets.GCP_SA_KEY }}' > cluster_gke/playbooks/temp.json

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GPC_PROJECT_ID }}

      - name: Authenticate with Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Instalar dependencias de Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible google-auth requests 
          ansible-galaxy collection install google.cloud

      - name: Ejecutar playbook
        run: |
          ansible-playbook -v -i cluster_gke/inventories/hosts.yaml cluster_gke/playbooks/create-cluster-gke.yaml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
          GPC_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_NOMBRE_CLUSTER: alambre-cluster-gke
          #CLUSTER_VERSION: ${{ secrets.CLUSTER_VERSION }}